module.exports = {
  PDF_TITLE: 'Propuesta de Estimación',
  PDF_CLIENT_LABEL: 'Cliente',
  PDF_DATE_LABEL: 'Fecha',
  PDF_PROJECT_SUMMARY: 'Resumen de Proyecto',
  PDF_PROJECT_TYPE: 'Tipo de proyecto',
  PDF_COMPLEXITY: 'Complejidad',
  PDF_PAGES: 'Páginas',
  PDF_INTEGRATIONS: 'Integraciones',
  PDF_FEATURES: 'Características',
  PDF_COST_BREAKDOWN: 'Desglose de Costos',
  PDF_BASE: 'Base',
  PDF_FEATURES_PRICE: 'Características',
  PDF_COMPLEXITY_MULTIPLIER: 'Complejidad',
  PDF_ESTIMATED_TIME: 'Tiempo estimado',
  PDF_TOTAL: 'Total estimado',
  PDF_CURRENCY: '$',
  PDF_WEEKS: 'semanas',
  PDF_NA: 'N/A',
};
